### ISSUE TITLE
Possible timezone wrong offset

### ISSUE THREAD

**Issue by diogo-rosa-everdelta** [tkuchiki/go-timezone#10]
Hi tkuchiki,

First of all thank you for the cool lib, appreciate it.
Just to make one thing clear, the BST timezone is UTC + 1 (https://www.timeanddate.com/time/zones/bst), so why the offset is 39600?

Thank you,
Diogo Rosa

**Comment by tkuchiki** [comment]
Hi diogo-oceanfone,

Thank you for reporting!
I will confirm it.

**Comment by diogo-oceanfone** [comment]
Thank you!

**Comment by tkuchiki** [comment]
I understand the problem.
BST has more than one meaning.

- Bangladesh Standard Time
- Bougainville Standard Time
- British Summer Time

Bougainville Standard Time is 39600 offset.

I have to fix this issue.
Sorry, It's going to take some time.

**Comment by tkuchiki** [comment]
I'm sorry for replying so late.

I released the https://github.com/tkuchiki/go-timezone/releases/tag/v0.2.0 .
An error is now returned for ambiguous abbreviations such as BST.
I wrote a godoc on how to use it, so take a look at it. 
https://godoc.org/github.com/tkuchiki/go-timezone

**Comment by tkuchiki** [comment]
I will close this issue for now.
If you have any problems, please re-open this issue.
