### ISSUE TITLE
Exporting "offsets" and "timezones"

### ISSUE THREAD

**Issue by Zamiell** [tkuchiki/go-timezone#2]
Hello; thanks for the excellent library, which I just found from a google search.

Is there a particular reason why you didn't export the help "offsets" and "timezones" variables? Unfortunately, I've had to copy paste them into my own program so that I can use them with the [dateparser](https://godoc.org/github.com/kierdavis/dateparser) module.

**Comment by tkuchiki** [comment]
Thank you for using!

>Is there a particular reason why you didn't export the help "offsets" and "timezones" variables? 

Because of to avoid unintended consequences.
I provide a function that returns "offsets" and "timezones".
One moment, please.

**Comment by tkuchiki** [comment]
@Zamiell Added `GetAllOffsets()` and `GetAllTimezones()` (https://github.com/tkuchiki/go-timezone/pull/3).
Is it okay?

**Comment by Zamiell** [comment]
yes, thank you!
