### ISSUE TITLE
Can you add usage examples？

### ISSUE THREAD

**Issue by Jeremy-Run** [tkuchiki/go-timezone#27]
It's not convenient to use without examples

**Comment by tkuchiki** [comment]
Do you need a more practical example than this one https://pkg.go.dev/github.com/tkuchiki/go-timezone#pkg-examples ?

**Comment by Jeremy-Run** [comment]
Thank you for you reply.
This is too complicated, I want a primer.
Looking forward to your support.😁

**Comment by tkuchiki** [comment]
For example, what kind of things do you want?
If you know of any other library examples, please share them with me.
