### ISSUE TITLE
could not convert from UTC to EST in Linux

### ISSUE THREAD

**Issue by vk18vk** [tkuchiki/go-timezone#4]
tried converting an UTC time to EST time but still getting same time as UTC
2018-03-14 12:58:18 +0000 UTC
after converting also showing same time
2018-03-14 12:58:18 +0000 UTC
Platform: linux

**Comment by tkuchiki** [comment]
Thanks for reporting the issue.
I will fix it.
Please wait a moment.

**Comment by vk18vk** [comment]
@tkuchiki thanks for replying,yes please

**Comment by tkuchiki** [comment]
@vk18vk Fixed! https://github.com/tkuchiki/go-timezone/pull/5

**Comment by vk18vk** [comment]
@tkuchiki thanks for updating

**Comment by tkuchiki** [comment]
Please close the issue if there is no problem!
